# Generated by Django 5.1.2 on 2024-10-29 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instituicao', models.CharField(choices=[('', 'Selececione sua Instituição'), ('UNIVESP', 'Univesp'), ('OUTRA', 'Outra Instituição')], max_length=100)),
                ('is_formado', models.CharField(blank=True, choices=[('', 'Situação do Curso'), ('CONCLUÍDO', 'Concluído'), ('EM ANDAMENTO', 'Em andamento')], max_length=100, null=True)),
                ('outra_instituicao', models.CharField(blank=True, max_length=100, null=True)),
                ('outro_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.CharField(blank=True, choices=[('', 'Selecione seu curso'), ('ENG_COMP', 'Engenharia de Computação'), ('ENG_PROD', 'Engenharia de Produção'), ('C_DADOS', 'Ciência de Dados'), ('TEC_INFO', 'Tecnologia da Informação'), ('MAT', 'Licenciatura em Matemática'), ('PED', 'Licenciatura em Pedagogia'), ('LET', 'Licenciatura em Letras')], max_length=100, null=True)),
                ('semestre', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Semestre')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnuncianteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('cargo', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
