# Generated by Django 5.1.2 on 2024-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncianteprofile',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Empresa'),
        ),
    ]
