# Generated by Django 5.1.2 on 2024-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_anuncianteprofile_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncianteprofile',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anuncianteprofile',
            name='instituicao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituição'),
        ),
    ]
